<?php
$titles = array(
	'meta_title' => 'Profis CMS {version} installation wizard',
	'title' => 'Profis CMS {version} installation wizard',
	'meta_title_requirements' => 'Profis CMS {version} requirements',
	'title_requirements' => 'Profis CMS {version} requirements',
	'mysql_requirement' => 'Please make sure you have MySQL {min_mysql_version} upwards.',
	'requirement' => 'Requirement',
	'available' => 'Available',
	'button_continue_to_install' => 'Continue to install',
	'fix_problems_and' => 'Please fix these problems and ',
	'button_test_again' => 'test again',
	'yes' => 'Yes',
	'no' => 'No',
	'req_pdo' => 'PDO support',
	'req_pdo_mysql' => 'PDO supports MySQL',
	'req_mod_rewrite' => 'Mod_rewrite enabled',
	'req_version' => 'version',
	'req_config_file_exists' => 'Configuration file exists',
	'req_config_file_writable' => 'Configuration file is writable',
	
	'db_info' => 'Database configuration',
	'db_driver' => 'Driver',
	'db_host' => 'Server (host)',
	'db_port' => 'Port',
	'db_user' => 'User',
	'db_password' => 'Password',
	'db_name' => 'Name',
	'db_prefix' => 'Table prefix',
	
	'required' => 'Required',
	'optional' => 'Optional',
	
	'db_port_expl' => 'Default MySQL: 3306; default PostgreSQL: 5432',
	'db_password_expl' => 'If there is no database password, leave it blank.',
	'db_name_expl' => 'You have to create a database manually and enter its name here.',
	'db_prefix_expl' => '',
	
	'other_info' => 'User information',
	'admin_name' => 'Administrator username',
	'admin_pass' => 'Administrator password',
	'admin_name_expl' => 'Allows you to specify a custom username for the administrator. Default: admin',
	'admin_pass_expl' => 'Allows you to specify a custom password for the administrator. Default: admin',
	'button_install' => 'Install now',
	
	'install_success' => 'Profis CMS was succesfully installed!',
	'go_to_admin' => 'Go to admin',
	'go_to_frontend' => 'Go to frontend',
	'install_failed_db' => 'Profis CMS could not connect to the database and has not been installed.',
	'install_error' => 'The following error has occured',
	'config_write_error' => 'Config file could not be written!',
	'try_again' => 'Click here to try again',
	
);