tinyMCE.addI18n('en.advform_dlg',{
tab_general:"General",
tab_appearance:"Appearance",
tab_advanced:"Advanced",
general:"General",
title:"Title",
preview:"Preview",
constrain_proportions:"Constrain proportions",
langdir:"Language direction",
langcode:"Language code",
long_desc:"Long description link",
style:"Style",
classes:"Classes",
ltr:"Left to right",
rtl:"Right to left",
id:"Id",
map:"Form map",
swap_form:"Swap form",
alt_form:"Alternative form",
mouseover:"for mouse over",
mouseout:"for mouse out",
misc:"Miscellaneous",
example_img:"Appearance preview form",
missing_alt:"Are you sure you want to continue without including an Form Description? Without it the form may not be accessible to some users with disabilities, or to those using a text browser, or browsing the Web with forms turned off.",
dialog_title:"Insert/edit form",
src:"Form URL",
alt:"Form description",
list:"Form list",
border:"Border",
dimensions:"Dimensions",
vspace:"Vertical space",
hspace:"Horizontal space",
align:"Alignment",
align_baseline:"Baseline",
align_top:"Top",
align_middle:"Middle",
align_bottom:"Bottom",
align_texttop:"Text top",
align_textbottom:"Text bottom",
align_left:"Left",
align_right:"Right",
form_list:"Form list"
});